version: 0.0
os: linux
files:
  - source: ./config
    destination: /var/www/html
  - source: ./src
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: root
    group: root
    mode: 777
